### ISSUE TITLE
Problems with default zope.interface in Unbuntu 14.04.2

### ISSUE THREAD

**Issue by mikeadamz** [letsencrypt/letsencrypt#418]
The zope.interface installed with Ubuntu 14.04 LTS is not new enough to support letsencrypt. It can be upgraded manually via pip, but the old version is a dependency for other things shipped with Ubuntu:

root@web:~# letsencrypt 
Traceback (most recent call last):
  File "/usr/local/bin/letsencrypt", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (zope.interface 4.0.5 (/usr/lib/python2.7/dist-packages), Requirement.parse('zope.interface>=4.1.0'))
root@web:~# 

root@web:~# apt-cache showpkg python-zope.interface
Package: python-zope.interface
Versions: 
4.0.5-1ubuntu4 (/var/lib/apt/lists/us-west-1.ec2.archive.ubuntu.com_ubuntu_dists_trusty_main_binary-amd64_Packages) (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/apt/lists/us-west-1.ec2.archive.ubuntu.com_ubuntu_dists_trusty_main_binary-amd64_Packages
                  MD5: 805f005a76a0fe3fbb6fb54d05dea254
 Description Language: en
                 File: /var/lib/apt/lists/us-west-1.ec2.archive.ubuntu.com_ubuntu_dists_trusty_main_i18n_Translation-en
                  MD5: 805f005a76a0fe3fbb6fb54d05dea254

Reverse Depends: 
  python-maas-provisioningserver,python-zope.interface
  python-django-maas,python-zope.interface
  maas-cluster-controller,python-zope.interface
  python-schooltool,python-zope.interface
  python-maas-provisioningserver,python-zope.interface
  python-django-maas,python-zope.interface
  maas-cluster-controller,python-zope.interface
  tahoe-lafs,python-zope.interface
  slapos-client,python-zope.interface
  sat-xmpp-core,python-zope.interface
  python-zope.viewlet,python-zope.interface
  python-zope.traversing,python-zope.interface
  python-zope.testrunner,python-zope.interface
  python-zope.testing,python-zope.interface
  python-zope.testbrowser,python-zope.interface
  python-zope.tales,python-zope.interface
  python-zope.tal,python-zope.interface
  python-zope.sqlalchemy,python-zope.interface
  python-zope.size,python-zope.interface
  python-zope.site,python-zope.interface
  python-zope.session,python-zope.interface
  python-zope.server,python-zope.interface
  python-zope.sendmail,python-zope.interface
  python-zope.securitypolicy,python-zope.interface
  python-zope.security,python-zope.interface
  python-zope.schema,python-zope.interface
  python-zope.publisher,python-zope.interface
  python-zope.ptresource,python-zope.interface
  python-zope.proxy,python-zope.interface
  python-zope.processlifetime,python-zope.interface
  python-zope.principalregistry,python-zope.interface
  python-zope.principalannotation,python-zope.interface
  python-zope.pluggableauth,python-zope.interface
  python-zope.password,python-zope.interface
  python-zope.pagetemplate,python-zope.interface
  python-zope.minmax,python-zope.interface
  python-zope.mimetype,python-zope.interface
  python-zope.login,python-zope.interface
  python-zope.location,python-zope.interface
  python-zope.lifecycleevent,python-zope.interface
  python-zope.keyreference,python-zope.interface
  python-zope.intid,python-zope.interface
  python-zope.index,python-zope.interface
  python-zope.html,python-zope.interface
  python-zope.formlib,python-zope.interface
  python-zope.filerepresentation,python-zope.interface
  python-zope.file,python-zope.interface
  python-zope.exceptions,python-zope.interface
  python-zope.error,python-zope.interface
  python-zope.dublincore,python-zope.interface
  python-zope.copypastemove,python-zope.interface
  python-zope.copy,python-zope.interface
  python-zope.contentprovider,python-zope.interface
  python-zope.container,python-zope.interface
  python-zope.configuration,python-zope.interface
  python-zope.componentvocabulary,python-zope.interface
  python-zope.component,python-zope.interface 3.8.0
  python-zope.catalog,python-zope.interface
  python-zope.browserresource,python-zope.interface
  python-zope.browserpage,python-zope.interface
  python-zope.browsermenu,python-zope.interface
  python-zope.browser,python-zope.interface
  python-zope.broken,python-zope.interface
  python-zope.authentication,python-zope.interface
  python-zope.applicationcontrol,python-zope.interface
  python-zope.app.wsgi,python-zope.interface
  python-zope.app.testing,python-zope.interface
  python-zope.app.server,python-zope.interface
  python-zope.app.security,python-zope.interface
  python-zope.app.schema,python-zope.interface
  python-zope.app.rotterdam,python-zope.interface
  python-zope.app.renderer,python-zope.interface
  python-zope.app.publisher,python-zope.interface
  python-zope.app.publication,python-zope.interface
  python-zope.app.pagetemplate,python-zope.interface
  python-zope.app.localpermission,python-zope.interface
  python-zope.app.locales,python-zope.interface
  python-zope.app.i18n,python-zope.interface
  python-zope.app.http,python-zope.interface
  python-zope.app.generations,python-zope.interface
  python-zope.app.form,python-zope.interface
  python-zope.app.exception,python-zope.interface
  python-zope.app.dependable,python-zope.interface
  python-zope.app.content,python-zope.interface
  python-zope.app.container,python-zope.interface
  python-zope.app.component,python-zope.interface
  python-zope.app.broken,python-zope.interface
  python-zope.app.basicskin,python-zope.interface
  python-zope.app.authentication,python-zope.interface
  python-zope.app.appsetup,python-zope.interface
  python-zope.app.applicationcontrol,python-zope.interface
  python-zope.annotation,python-zope.interface
  python-zodb,python-zope.interface
  python-zc.table,python-zope.interface
  python-zc.resourcelibrary,python-zope.interface
  python-zc.i18n,python-zope.interface
  python-zc.datetimewidget,python-zope.interface
  python-zc.catalog,python-zope.interface
  python-z3c.template,python-zope.interface
  python-z3c.rml,python-zope.interface
  python-z3c.pt,python-zope.interface
  python-z3c.optionstorage,python-zope.interface
  python-z3c.macro,python-zope.interface
  python-z3c.form,python-zope.interface
  python-z3c.autoinclude,python-zope.interface
  python-ubuntu-sso-client.tests,python-zope.interface
  python-txzmq,python-zope.interface
  python-txtorcon,python-zope.interface 3.6.1
  python-transaction,python-zope.interface
  python-schooltool.lyceum.journal,python-zope.interface
  python-schooltool.intervention,python-zope.interface
  python-schooltool.gradebook,python-zope.interface
  python-schooltool,python-zope.interface
  python-repoze.who,python-zope.interface
  python-repoze.what,python-zope.interface
  python-repoze.sphinx.autointerface,python-zope.interface
  python-qt4reactor,python-zope.interface
  python-pyxmpp,python-zope.interface
  python-pyramid,python-zope.interface 3.8.0
  python-martian,python-zope.interface
  python-lazr.restful,python-zope.interface
  python-lazr.lifecycle,python-zope.interface
  python-lazr.enum,python-zope.interface
  python-lazr.delegates,python-zope.interface
  python-lazr.batchnavigator,python-zope.interface
  python-hurry.query,python-zope.interface
  python-grokcore.component,python-zope.interface
  python-foolscap,python-zope.interface
  python-flufl.bounce,python-zope.interface
  pybridge-common,python-zope.interface
  ibid,python-zope.interface
  deejayd,python-zope.interface
  calendarserver,python-zope.interface 4
  python-zope.interface-dbg,python-zope.interface 4.0.5-1ubuntu4
  python-ubuntu-sso-client,python-zope.interface
  python-txtftp,python-zope.interface
  python-txlongpoll,python-zope.interface
  python-twisted-core,python-zope.interface 3.6
  python-maas-provisioningserver,python-zope.interface
  python-lazr.restfulclient,python-zope.interface
  python-django-maas,python-zope.interface
  maas-cluster-controller,python-zope.interface
Dependencies: 
4.0.5-1ubuntu4 - python (2 2.7) python (3 2.8) python:any (2 2.7.1-0ubuntu2) python-pkg-resources (0 (null)) libc6 (2 2.2.5) python-zope (0 (null)) python-zopeinterface (0 (null)) zope3 (0 (null)) python-zope (0 (null)) python-zopeinterface (0 (null)) 
Provides: 
4.0.5-1ubuntu4 - python2.7-zope.interface python-zopeinterface python-zope 
Reverse Provides: 
root@web:~# 

root@web:~# pip install --upgrade zope.interface
Downloading/unpacking zope.interface from https://pypi.python.org/packages/source/z/zope.interface/zope.interface-4.1.2.tar.gz#md5=04298faeaa70b4f3b23fa2ae8987262c
  Downloading zope.interface-4.1.2.tar.gz (919kB): 919kB downloaded
  Running setup.py (path:/tmp/pip_build_root/zope.interface/setup.py) egg_info for package zope.interface
    
    warning: no previously-included files matching '*.dll' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
Downloading/unpacking setuptools from https://pypi.python.org/packages/3.4/s/setuptools/setuptools-15.2-py2.py3-none-any.whl#md5=fc72e6c9622b25026fb8984a156b8719 (from zope.interface)
  Downloading setuptools-15.2-py2.py3-none-any.whl (501kB): 501kB downloaded
Installing collected packages: zope.interface, setuptools
  Found existing installation: zope.interface 4.0.5
    Uninstalling zope.interface:
      Successfully uninstalled zope.interface
  Running setup.py install for zope.interface
    
    warning: no previously-included files matching '*.dll' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    building 'zope.interface._zope_interface_coptimizations' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/zope/interface/_zope_interface_coptimizations.c -o build/temp.linux-x86_64-2.7/src/zope/interface/_zope_interface_coptimizations.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/zope/interface/_zope_interface_coptimizations.o -o build/lib.linux-x86_64-2.7/zope/interface/_zope_interface_coptimizations.so
    Skipping installation of /usr/local/lib/python2.7/dist-packages/zope/__init__.py (namespace package)
    Installing /usr/local/lib/python2.7/dist-packages/zope.interface-4.1.2-nspkg.pth
  Found existing installation: setuptools 3.3
    Uninstalling setuptools:
      Successfully uninstalled setuptools
Successfully installed zope.interface setuptools
Cleaning up...
root@web:~# letsencrypt 
Traceback (most recent call last):
  File "/usr/local/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1', 'console_scripts', 'letsencrypt')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2672, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2345, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2351, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/software/lets-encrypt-preview/letsencrypt/cli.py", line 9, in <module>
    import zope.component
  File "/usr/local/lib/python2.7/dist-packages/zope/component/__init__.py", line 19, in <module>
    from zope.interface import named
ImportError: cannot import name named
root@web:~# apt-get remove zope.interface
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'python3-zope.interface-dbg' for regex 'zope.interface'
Note, selecting 'python3.4-zope.interface' for regex 'zope.interface'
Note, selecting 'python-zope.interface-dbg' for regex 'zope.interface'
Note, selecting 'python2.7-zope.interface' for regex 'zope.interface'
Note, selecting 'python-zope.interface' for regex 'zope.interface'
Note, selecting 'python3-zope.interface' for regex 'zope.interface'
Note, selecting 'python-zope.interface' instead of 'python2.7-zope.interface'
Note, selecting 'python3-zope.interface' instead of 'python3.4-zope.interface'
Package 'python-zope.interface-dbg' is not installed, so not removed
Package 'python3-zope.interface' is not installed, so not removed
Package 'python3-zope.interface-dbg' is not installed, so not removed
The following packages will be REMOVED:
  landscape-client landscape-common python-twisted-core python-twisted-names
  python-twisted-web python-zope.interface
0 upgraded, 0 newly installed, 6 to remove and 4 not upgraded.
After this operation, 10.1 MB disk space will be freed.
Do you want to continue? [Y/n] n        
Abort.
root@web:~#

**Comment by kuba** [comment]
Please use virtualenv as described in http://letsencrypt.readthedocs.org/en/latest/using.html#installation

**Comment by kuba** [comment]
@mikeadamz, are you still having this issue? If not, then please close this bug report. Thanks!

**Comment by mikeadamz** [comment]
The problem still exists. I was able to get around it with a virtualenv,
but there's still the inherent incompatibility with the default Ubuntu
installation.

On Tue, Jun 2, 2015 at 12:22 AM, Jakub Warmuz <notifications@github.com>
wrote:

> @mikeadamz <https://github.com/mikeadamz>, are you still having this
> issue? If not, then please close this bug report. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/letsencrypt/lets-encrypt-preview/issues/418#issuecomment-107836023>
> .
>



-- 
Mike Adams <mike.adams@unix-security.net>
Cell: 916.538.4013

"Any intelligent fool can make things bigger, more complex, and more
violent. It takes a touch of genius -- and a lot of courage -- to move in
the opposite direction."
-Albert Einstein

**Comment by kuba** [comment]
Well, this is what happens when system packages are mixed with `pip install` and this is why provided instructions require `virtualenv`. FYI proper Debian packages are on their way, thanks to @fmarier.

I believe this is resolved now.

**Comment by oxitech239** [comment]
still a problem today on 14.04, no debian have been made available

**Comment by kuba** [comment]
This bug is WONT FIX. We are still working on packaging.

**Comment by oxitech239** [comment]
Hi, 
  
It took a while but I found the commandline to use for building letsencrypt. 

If such would be applicable it would be nice to have this included in the Readme file. 
  
http://letsencrypt.readthedocs.org/en/latest/using.html 
  
virtualenv --no-site-packages -p python2 venv 
./venv/bin/pip install -r requirements.txt acme/ . letsencrypt-apache/ letsencrypt-nginx/ 
  
Br, 

Joris 

----- Oorspronkelijk bericht -----

Van: "Jakub Warmuz" <notifications@github.com> 
Aan: "letsencrypt/letsencrypt" <letsencrypt@noreply.github.com> 
Cc: "oxitech239" <oxitech@telenet.be> 
Verzonden: Vrijdag 21 augustus 2015 07:59:39 
Onderwerp: Re: [letsencrypt] Problems with default zope.interface in Unbuntu 14.04.2 (#418) 



This bug is WONT FIX. We are still working on packaging.
